TCONST = "tconst"  # string
TITLE_TYPE = "titleType"  # string
PRIMARY_TITLE = "primaryTitle"  # string
ORIGINAL_TITLE = "originalTitle"  # string
IS_ADULT = "isAdult"  # boolean
START_YEAR = "startYear"  # integer (YYYY)
END_YEAR = "endYear"  # integer (YYYY)
RUNTIME_MINUTES = "runtimeMinutes"  # integer
GENRES = "genres"  # array of strings
TITLE_ID = "titleId"  # string
ORDERING = "ordering"  # integer
TITLE = "title"  # string
REGION = "region"  # string
LANGUAGE = "language"  # string
TYPES = "types"  # array of strings
ATTRIBUTES = "attributes"  # array of strings
IS_ORIGINAL_TITLE = "isOriginalTitle"  # boolean
DIRECTORS = "directors"  # array of nconsts (string)
WRITERS = "writers"  # array of nconsts (string)
PARENT_TCONST = "parentTconst"  # string
SEASON_NUMBER = "seasonNumber"  # integer
EPISODE_NUMBER = "episodeNumber"  # integer
NCONST = "nconst"  # string
CATEGORY = "category"  # string
JOB = "job"  # string
CHARACTERS = "characters"  # string
AVERAGE_RATING = "averageRating"  # float
NUM_VOTES = "numVotes"  # integer
PRIMARY_NAME = "primaryName"  # string
BIRTH_YEAR = "birthYear"  # string
DEATH_YEAR = "deathYear"  # string
PRIMARY_PROFESSION = "primaryProfession"  # array of strings
KNOWN_FOR_TITLES = "knownForTitles"  # array of tconsts (string)
